use std::str::FromStr;
use crate::asm::ast::LabelOrOpcode;

grammar;

pub LabelOrOpcodes: Vec<LabelOrOpcode<'input>> = {
	(<LabelOrOpcode>)*
}

LabelOrOpcode: LabelOrOpcode<'input> = {
	<Ident> ":" "\n" => LabelOrOpcode::Label(<>),
	<Opcode>,
}

Opcode: LabelOrOpcode<'input> = {
	<Ident> (<U8>)* "\n" => LabelOrOpcode::Opcode(<>)
}

Ident: &'input str = r"[_a-zA-Z][_a-zA-Z0-9]*";
U8: u8 = r"[0-9]+" => u8::from_str(<>).unwrap();
