[package]
name = "nqc"
version = "0.0.0"
edition = "2021"
authors = ["David Young <david@thedavidyoung.co.uk>"]
license = "MPL-2.0"
repository = "https://github.com/bricks-rs/rcx"
description = "[wip] Compiler for the NQC programming language for Lego RCX"
#readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strum = { version = "0.26.1", features = ["derive"] }

[dev-dependencies]
insta = "1.35.1"
pretty_assertions = "1.4.0"
