// This file is automatically generated

{% for opcode in opcodes %}
pub struct {{ opcode.name }} {
    {% for param in opcode.request.params %}
    {{ param.name }}: {{ param.ty }},
    {% endfor %}
}
pub struct {{ opcode.name }}Response {
    {% for param in opcode.response.params %}
    pub struct {{ param.name }}: {{ param.ty }},
    {% endfor %}
}

impl {{ opcode.name }} {
    pub const REQUEST:u8 = {{ opcode.request.opcode }};
    pub const RESPONSE:u8 = {{ opcode.response.opcode }};
}

{% endfor %}
